"""
Django settings for school_site project.

Generated by 'django-admin startproject' using Django 5.0a1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""
import os
from pathlib import Path
from . import myconfig

# change sqlite3 package by pysqlite3 (new version of sqlite)
__import__('pysqlite3')
import sys
sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')
#sys.path.append("../../")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = myconfig.BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = myconfig.SECRET_KEY  # "django-insecure-jo@)3541=mo=s&lj35oj5#w*9d_zx1bw)f8xva973opr8zio9e"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = myconfig.DEBUG

ALLOWED_HOSTS = ['127.0.0.1', 'labson.ru', 'www.labson.ru']


# Application definition

INSTALLED_APPS = [
    "main",
    "ckeditor",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    'csp.middleware.CSPMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "school_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "school_site.wsgi.application"


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = "static/"

tmp = os.path.dirname(__file__)
tmp, _ = os.path.split(tmp)
tmp, _ = os.path.split(tmp)

STATIC_ROOT = tmp + "/static/"
#STATIC_ROOT = myconfig.STATIC_ROOT

# Default primary key field type
# https://docs.djangoproject.com/en/dev/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
        'height': 300,
        'width': '100%',
        'removePlugins': 'stylesheetparser',
        'extraAllowedContent': 'iframe[*]',
    },
}

# Content Security Policy
CSP_DEFAULT_SRC = ("'self'", 'mc.yandex.ru', 'yandex.ru', 'vk.com', 'www.vk.com', 'youtube.com', 'www.youtube.com')
CSP_IMG_SRC = ("'self'", "*")
CSP_STYLE_SRC_ATTR = ("'unsafe-inline'", )
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "127.0.0.1", 'labson.ru', 'www.labson.ru', 'yandex.ru')
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "127.0.0.1", 'labson.ru', 'www.labson.ru', 'mc.yandex.ru', 'yandex.ru')
CSP_FRAME_ANCESTORS = ("'self'", 'yandex.ru', 'vk.com', 'www.vk.com', 'youtube.com', 'www.youtube.com')

CSP_INCLUDE_NONCE_IN = ['script-src', 'style-src']